// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gatewaympesa "github.com/ManuelMassora/servicoJa-api/internal/infra/gateway_mpesa"
	mock "github.com/stretchr/testify/mock"
)

// PagamentoUseCase is an autogenerated mock type for the PagamentoUseCase type
type PagamentoUseCase struct {
	mock.Mock
}

// ConfirmarPagamentoC2B provides a mock function with given fields: ctx, referencia
func (_m *PagamentoUseCase) ConfirmarPagamentoC2B(ctx context.Context, referencia string) error {
	ret := _m.Called(ctx, referencia)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmarPagamentoC2B")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, referencia)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IniciarPagamentoC2B provides a mock function with given fields: ctx, idPagamento, telefone
func (_m *PagamentoUseCase) IniciarPagamentoC2B(ctx context.Context, idPagamento uint, telefone string) error {
	ret := _m.Called(ctx, idPagamento, telefone)

	if len(ret) == 0 {
		panic("no return value specified for IniciarPagamentoC2B")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, idPagamento, telefone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessarCallbackMpesa provides a mock function with given fields: ctx, payload
func (_m *PagamentoUseCase) ProcessarCallbackMpesa(ctx context.Context, payload gatewaympesa.MpesaCallbackPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ProcessarCallbackMpesa")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gatewaympesa.MpesaCallbackPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessarCancelamentoComReembolso provides a mock function with given fields: ctx, idServico, idUsuarioCancelou
func (_m *PagamentoUseCase) ProcessarCancelamentoComReembolso(ctx context.Context, idServico uint, idUsuarioCancelou uint) error {
	ret := _m.Called(ctx, idServico, idUsuarioCancelou)

	if len(ret) == 0 {
		panic("no return value specified for ProcessarCancelamentoComReembolso")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, idServico, idUsuarioCancelou)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessarPagamentoPrestador provides a mock function with given fields: ctx, idServico
func (_m *PagamentoUseCase) ProcessarPagamentoPrestador(ctx context.Context, idServico uint) error {
	ret := _m.Called(ctx, idServico)

	if len(ret) == 0 {
		panic("no return value specified for ProcessarPagamentoPrestador")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, idServico)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessarQuerySimulada provides a mock function with given fields: ctx, referencia
func (_m *PagamentoUseCase) ProcessarQuerySimulada(ctx context.Context, referencia string) error {
	ret := _m.Called(ctx, referencia)

	if len(ret) == 0 {
		panic("no return value specified for ProcessarQuerySimulada")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, referencia)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPagamentoUseCase creates a new instance of PagamentoUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPagamentoUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PagamentoUseCase {
	mock := &PagamentoUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
